In [1]:
import pandas as pd

In [2]:
## Data Ingestions step
df=pd.read_csv("data/census_income1.csv")

In [3]:
df.head()

,id,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
0,0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [4]:
#dropping id column
df=df.drop(labels=['id'],axis=1)

In [14]:
##converting education_num from int to object
df["education_num"]=df["education_num"].astype("str")

In [15]:
## Independent and dependent features
X=df.drop(labels=["class"],axis=1)
Y=df["class"]

In [16]:
# Define which columns should be onehot-encoded and which should be scaled
numerical_cols=["age","fnlwgt","capital_gain","capital_loss","hours_per_week"]
category_cols=["workclass","education","education_num","marital_status","occupation","relationship","race","sex","native_country"]

In [17]:
# Define onehot encoded variable
workclass_cat=[' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',' Local-gov', ' others', ' Self-emp-inc', ' Without-pay', ' Never-worked']
education_cat=[' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',' Preschool', ' 12th']
education_num_cat=["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16"]
marital_status_cat=[' Never-married', ' Married-civ-spouse', ' Divorced',' Married-spouse-absent', ' Separated', ' Married-AF-spouse',' Widowed']
occupation_cat=[' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',' Tech-support', ' others', ' Protective-serv', ' Armed-Forces',' Priv-house-serv']
relationship_cat=[' Not-in-family', ' Husband', ' Wife', ' Own-child', ' Unmarried',' Other-relative']
race_cat=[' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',' Other']
sex_cat=[' Male', ' Female']
native_country_cat=[' United-States', ' Cuba', ' Jamaica', ' India', ' others',' Mexico', ' South', ' Puerto-Rico', ' Honduras', ' England',' Canada', ' Germany', ' Iran', ' Philippines', ' Italy',' Poland', ' Columbia', ' Cambodia', ' Thailand', ' Ecuador',' Laos', ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',' Ireland', ' Hungary', ' Holand-Netherlands']

In [22]:
#importing some libraries
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import log_loss

from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OneHotEncoder # One hot encoding Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [19]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())

    ]

)
#Categorical onehote encoder pipeline
cat_onehot_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ("onehotencoder",OneHotEncoder(categories=[workclass_cat,education_cat,education_num_cat,marital_status_cat,occupation_cat,relationship_cat,race_cat,sex_cat,native_country_cat],sparse=False)),
    ("scaler",StandardScaler())
    ]

)



preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
("cat_onehot_pipeline",cat_onehot_pipeline,category_cols)

])

In [20]:
##defining test and train data
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [21]:
#fitting train and test data ,and transforming train data
X_train=pd.DataFrame(preprocessor.fit_transform(X_train))
X_test=pd.DataFrame(preprocessor.transform(X_test))
X_train.head()

g:\practice\plmkn\project-census-income\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,0,1,2,3,4,5,6,7,8,9,...,113,114,115,116,117,118,119,120,121,122
0,-0.184470,-0.073413,-0.146309,-0.217065,-0.036989,-0.203928,-0.290079,0.658445,-0.17563,-0.261422,...,-0.022952,-0.017528,-0.018738,-0.031783,-0.033137,-0.048278,-0.022952,-0.024792,-0.019875,-0.006624
1,-1.510861,-0.456592,0.149568,-0.217065,-1.658547,-0.203928,-0.290079,0.658445,-0.17563,-0.261422,...,-0.022952,-0.017528,-0.018738,-0.031783,-0.033137,-0.048278,-0.022952,-0.024792,-0.019875,-0.006624
2,-0.552912,0.231261,-0.146309,-0.217065,1.989959,-0.203928,-0.290079,0.658445,-0.17563,-0.261422,...,-0.022952,-0.017528,-0.018738,-0.031783,-0.033137,-0.048278,-0.022952,-0.024792,-0.019875,-0.006624
3,0.773479,0.829970,-0.146309,-0.217065,0.773790,-0.203928,-0.290079,0.658445,-0.17563,-0.261422,...,-0.022952,-0.017528,-0.018738,-0.031783,-0.033137,-0.048278,-0.022952,-0.024792,-0.019875,-0.006624
4,1.657740,-1.141907,-0.146309,-0.217065,-0.280223,-0.203928,-0.290079,-1.518731,-0.17563,-0.261422,...,-0.022952,-0.017528,-0.018738,-0.031783,-0.033137,-0.048278,-0.022952,-0.024792,-0.019875,-0.006624

In [23]:
#defining a function for model value prediction
import numpy as np
def evaluate_model(true, predicted):
    acc_score = accuracy_score(true, predicted)
    logloss=log_loss(true,predicted)
    report=classification_report(true, predicted, digits=3)
    confuse_matrix = confusion_matrix(true, predicted)
    return acc_score,logloss,report,confuse_matrix

In [24]:
##train multiple models
models={
    'LogisticRegression':LogisticRegression(penalty='none',random_state=0),
    'Lasso':LogisticRegression(penalty='l1', solver='liblinear',random_state=0),
    'Ridge':LogisticRegression(penalty='l2', solver='liblinear',random_state=0),
    'Elasticnet':LogisticRegression(penalty='elasticnet', solver='saga',l1_ratio=0.5,random_state=0)
}
trained_model_list=[]
model_list=[]
accuracy_score_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    acc_score,logloss,report,confuse_matrix=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("accuracy_score:",acc_score)
    print("log loss value:",logloss)
    print("report of classification:","\n",
          report)
    print("confusion_matrix:","\n",
          confuse_matrix)
    

    accuracy_score_list.append(acc_score)
    
    print('='*35)
    print('\n')

g:\practice\plmkn\project-census-income\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(

LogisticRegression
Model Training Performance
accuracy_score: 0.853618589415498
log loss value: 5.276120825717833
report of classification:
               precision    recall  f1-score   support

           0      0.883     0.932     0.907      7464
           1      0.731     0.600     0.659      2305

    accuracy                          0.854      9769
   macro avg      0.807     0.766     0.783      9769
weighted avg      0.847     0.854     0.848      9769

confusion_matrix:
 [[6956  508]
 [ 922 1383]]
===================================


Lasso
Model Training Performance
accuracy_score: 0.8538233186610708
log loss value: 5.2687416357517955
report of classification:
               precision    recall  f1-score   support

           0      0.883     0.932     0.907      7464
           1      0.732     0.601     0.660      2305

    accuracy                          0.854      9769
   macro avg      0.807     0.766     0.783      9769
weighted avg      0.847     0.854     0.849      9769

confusion_matrix:
 [[6956  508]
 [ 920 1385]]
===================================


Ridge
Model Training Performance
accuracy_score: 0.8539256832838571
log loss value: 5.265052040768777
report of classification:
               precision    recall  f1-score   support

           0      0.883     0.932     0.907      7464
           1      0.732     0.601     0.660      2305

    accuracy                          0.854      9769
   macro avg      0.808     0.766     0.783      9769
weighted avg      0.848     0.854     0.849      9769

confusion_matrix:
 [[6957  507]
 [ 920 1385]]
===================================


Elasticnet
Model Training Performance
accuracy_score: 0.8547446002661481
log loss value: 5.235535280904621
report of classification:
               precision    recall  f1-score   support

           0      0.883     0.934     0.908      7464
           1      0.736     0.599     0.661      2305

    accuracy                          0.855      9769
   macro avg      0.810     0.766     0.784      9769
weighted avg      0.848     0.855     0.849      9769

confusion_matrix:
 [[6969  495]
 [ 924 1381]]
===================================

g:\practice\plmkn\project-census-income\venv\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(